package com.amazonaws.shortify;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="ShortifyV1")
public class UrlItem {
	private String id;
	private String originalUrl;
	private String base62Id;
	private Long creationDate;
	private Long expirationDate;
	
	
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBHashKey(attributeName = "OriginalUrl")
	public String getOriginalUrl() {
		return originalUrl;
	}
	public void setOriginalUrl(String originalUrl) {
		this.originalUrl = originalUrl;
	}
	public String getBase62Id() {
		return base62Id;
	}
	
	@DynamoDBAttribute()
	public void setBase62Id(String base62Id) {
		this.base62Id = base62Id;
	}
	public Long getCreationDate() {
		return creationDate;
	}
	
	@DynamoDBAttribute()
	public void setCreationDate(Long creationDate) {
		this.creationDate = creationDate;
	}
	public Long getExpirationDate() {
		return expirationDate;
	}
	
	@DynamoDBAttribute()
	public void setExpirationDate(Long expirationDate) {
		this.expirationDate = expirationDate;
	}
	
	
}
